#!/bin/bash

#-------------------------------
# Generic SLURM script  -- MPI
#-------------------------------

#SBATCH -J rtm           # Job name
#SBATCH -o rtm.o.%j      # Output file (%j expands to jobID)
#SBATCH -e rtm.e.%j      # Error file (%j expands to jobID)
#SBATCH -p normal          # Queue name
#SBATCH -N 52              # Nodes requested
#SBATCH -n 104              # Total number of mpi tasks requested
#SBATCH -t 4:00:00        # Run time (hh:mm:ss)
#SBATCH -A TCCS            # Project account name
#SBATCH --mail-user=zhiguangxue@gmail.com # Email address
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes


export OMP_NUM_THREADS=12
ibrun tacc_affinity /work/02805/xue0810/lonestar/RSFSRC/user/zhiguang/sfmpilrrtm_ts --input=data.rsf --output=img1.rsf Fimg2=img2.rsf Fsrc=csource.rsf Fpadvel=vp.rsf verb=n taper=4 nb=60 nds=4 gpz=0 spx=802 spz=0 rnx=1301 ntau=201 dtau=0.004 tau0=-0.4
