#!/bin/bash

#-------------------------------
# Generic SLURM script  -- MPI
#-------------------------------

#SBATCH -J testrtm           # Job name
#SBATCH -o testrtm.o.%j      # Output file (%j expands to jobID)
#SBATCH -e testrtm.e.%j      # Error file (%j expands to jobID)
#SBATCH -p normal          # Queue name
#SBATCH -N 6              # Nodes requested
#SBATCH -n 12              # Total number of mpi tasks requested
#SBATCH -t 0:30:00        # Run time (hh:mm:ss)
#SBATCH -A TCCS            # Project account name
#SBATCH --mail-user=zhiguangxue@gmail.com # Email address
#SBATCH --mail-type=begin  # email me when the job starts
#SBATCH --mail-type=end    # email me when the job finishes


export OMP_NUM_THREADS=12
ibrun tacc_affinity /work/02805/xue0810/lonestar/RSFSRC/user/zhiguang/sfmpilrrtm_ts --input=testdata.rsf --output=img1.rsf Fimg2=img2.rsf Fsrc=csource.rsf Fpadvel=testvp.rsf verb=y taper=4 nb=60 nds=40 gpz=0 spx=802 spz=0 rnx=1301 ntau=201 dtau=0.004 tau0=-0.4
